### ISSUE TITLE
Add Feature

### ISSUE THREAD

**Issue by anuragpurwar** [akshaydugar/RichTextEditor#1]
Hi

Can you please add a feature for adding image from Gallery and Camera inside html text.

**Comment by akshaydugar** [comment]
Yes, I have a prototype implementation ready for adding inline images in the HTML.
The code to add image to the html is complete, but firing gallery/camera intent and handling the incoming image data is something that is still remaining. I plan to do that in a future release and may take time.

I can consider adding an API to add an image to the HTML which will take a Bitmap as a parameter, as that will take much less time, but then the UI to show add image button, firing/processing relevant intent, and getting the resultant Bitmap is something that you may have to do.

**Comment by akshaydugar** [comment]
Support for inline image is now added.
The Maven artifact is not updated yet, but you can download the source code and use it as a project.

There is a new listener in RichEditText class called ImageInsertListener. Implement that listener, it will give you a callback to onImageInsert method when user taps the image button. Here, you need your own code to allow user to import an image. Once user has selected the image, call the RichEditText's insertImage method, which will add the image to the HTML.

Note: The insert image method takes a URL, this can either be a network URL or a local content URI.
