### ISSUE TITLE
net::ERR_UNKNOWN_SCHEME

### ISSUE THREAD

**Issue by dun74fr** [akshaydugar/RichTextEditor#5]
Hi,
I am trying to integrate this RichTextEditor in my app. I think it's a great way to handle the problem (with a webview and a javascript editor). But I am facing a problem. The Editor shows and render the the text but every attempt to touch it or a action button open a 
"Webpage not available" 
The webpage at re-state://justifyLeft could not be loaded because:
net::ERR_UNKNOWN_SCHEME
Do I need to add some scheme declaration in the manifest ? I did not see any difference with the example project.
Hope you can help..
Thanks

**Comment by dun74fr** [comment]
I downloaded the last source code from github and it works. The maven version seems to be mixed between jsinterface and scheme..

**Comment by akshaydugar** [comment]
Hi
I haven't been able to update the maven artifact is quite some time.
I will get to that soon.
